version: '3'
services:
  api:
    container_name: api
    command: mix phx.server
    build: .
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    links:
      - db

  db:
    container_name: db
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=password