version: '3'
services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=password