version: '3'
services:
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    links:
      - db

  db:
    container_name: db
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=password